import numpy as np
from scipy.spatial import cKDTree
import os

def audit_connectivity(file_base, file_shifted, radius=1.8):
    """
    Analyzes topological reconfiguration between two lattice states.
    radius=1.8 is the standard H3 first-neighbor shell.
    """
    if not os.path.exists(file_base) or not os.path.exists(file_shifted):
        print("❌ Error: Export files not found. Run pillar7_geometry_bridge.py first.")
        return

    # Load data
    lat_a = np.loadtxt(file_base, delimiter=',', skiprows=1)
    lat_b = np.loadtxt(file_shifted, delimiter=',', skiprows=1)

    # Build KD-Trees
    tree_a = cKDTree(lat_a)
    tree_b = cKDTree(lat_b)

    # Find neighbors (bonds) within the critical radius
    pairs_a = tree_a.query_pairs(r=radius)
    pairs_b = tree_b.query_pairs(r=radius)

    # Topology Math
    maintained = pairs_a.intersection(pairs_b)
    broken = pairs_a - pairs_b
    formed = pairs_b - pairs_a
    stability = len(maintained) / len(pairs_a) if len(pairs_a) > 0 else 0

    print(f"\n--- 🛰 DAT CONNECTIVITY AUDIT (Pillar 8) ---")
    print(f"Total Bonds (Base):   {len(pairs_a)}")
    print(f"Total Bonds (Shifted):{len(pairs_b)}")
    print(f"-------------------------------------------")
    print(f"Bonds Maintained:     {len(maintained)}")
    print(f"Bonds Broken:         {len(broken)} (Signal Cut)")
    print(f"Bonds Formed:         {len(formed)} (New Path)")
    print(f"Topological Stability: {stability:.2%}")
    print(f"-------------------------------------------")

    if len(broken) > 0 or len(formed) > 0:
        print("✅ SUCCESS: Topological switching verified via bond reconfiguration.")
    else:
        print("⚠️ WARNING: No bond changes detected. Consider increasing Phason Angle.")

if __name__ == "__main__":
    # Point to the data generated by your Pillar 7 Bridge
    audit_connectivity('data/pillar7/h3_coordinates_base.csv', 'data/pillar7/h3_coordinates.csv')
